apiVersion: v1
kind: Service
metadata:
    name: "zubzero-11ef"
    labels:
        app: "zubzero-11ef"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "zubzero-11ef"